### ISSUE TITLE
First contribution: refactoring and improvements

### ISSUE THREAD

**Issue by bgbraga** [ibmtjbot/tjbotlib#1]
I forked it and changed some items. I will submit a pull request. If my changes are going in a right way I will continue maintain and improving it. I decided to change these points to take this lib more flexible to grow.

Changelog:
- TJBot have two setup parameters: credentials and config. To use the same logic config.js and samples were refactored to have these two objects and override what is necessary.
- Moved TJBot.prototype.defaultConfiguration to config.js making it easy to access the list of parameters and setup TJ.
- Now config.js could have all service parameters. If you don't like to use some service, just keep user and password as blank.
- For development purpose (minimize the raspberry dependency), the conversation service was tested in Mac using SOX in replacement of ALSA (works but speaker player are throwing an exception). So moved tests to Ubuntu using ALSA. It works fine with little adjusts. Readme updated.
- Added config.microphone for microphone hardware setup (card/device). It is necessary in some situations.
- Auto choose voice based on language and gender: Instead of set specific voice manually, in the initialization TJ will get tts voices available and choose one based on preferred language and gender.

**Comment by victordibia** [comment]
@bgbraga 
Thanks for the PR!
We'll review soon!!

-V.

**Comment by victordibia** [comment]
Merged! Thanks for the contribution @bgbraga
