### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by sarthak50** [ibmtjbot/tjbotlib#29]
Is it possible to integrate and run two or more modules together at once(Tone Analyzer & TTS/STT)

**Comment by victordibia** [comment]
Can you provide additional detail on this?
Would you like an application that uses both services? You can actually do that right now.
-V

**Comment by sarthak50** [comment]
Exactly yes,Please provide the procedures.....

**Comment by victordibia** [comment]
@sarthak50 ..  a good example of this would be to run the  [conversation recipe](https://github.com/ibmtjbot/tjbot/blob/master/recipes/conversation/conversation.js).

That shows how you use at least 3 modules - STT (tj.listen), TTS (tj.speak), and conversation (tj.converse). Other capabilites like vision recognition (tj.see), tone analyses (tj.analyzeTone), language translation (tj.translate) are also available.  Please see the documentation on the [tjbot library](https://github.com/ibmtjbot/tjbotlib) to learn more about these methods.

Let me know if you need additional assistance.
