### ISSUE TITLE
Feature: TJBot Startup Script

### ISSUE THREAD

**Issue by victordibia** [ibmtjbot/tjbotlib#4]
A bootstrap script that prepares a stock rpi with the stuff it needs to “become” tjbot — e.g. installing / configuring alsa, blacklisting certain kernel modules, checking out tjbot code, performing hardware tests to make sure the user hooked up everything on the right pins etc.

- Install configure alsa
- Install configure latest nodejs, npm
- blacklist certain kernel modules (sound/led interference problem)
- Checkout TJBot code
- Perform hardware tests .. servo, led, mic, speaker

- Also check for Raspberry PI version. RPi v2 needs some additional installation steps

upgrade nodejs, npm, node-gyp and gcc.  
https://github.com/audstanley/NodeJs-Raspberry-Pi
https://github.com/nodejs/node-gyp/issues/809
https://community.thinger.io/t/starting-with-the-raspberry-pi/36

**Comment by jweisz** [comment]
Implemented in main tjbot repo.
