### ISSUE TITLE
Allow for custom URLs to pass to the SDK in tjbot library

### ISSUE THREAD

**Issue by Brianawalker** [ibmtjbot/tjbotlib#41]
The TJ bot library hard-codes the URL to https://stream.watsonplatform.net/speech-to-text/api/ . And in cases where clients are operating services outside of the US-region, it will be necessary to change the URL to gain access to the service. For example, Speech to text services created in this Sydney region will need to use the endpoint https://gateway-syd.watsonplatform.net/speech-to-text/api . Please enable custom URLs to pass to the SDK in this library.

**Comment by jweisz** [comment]
Great suggestion! Please check out this branch and let me know if it works for you (I haven't tested this at all so hopefully I didn't make any typos…)
https://github.com/ibmtjbot/tjbotlib/tree/feature/jw-customurl

If this is good, I'll merge it in to master and bump the lib to v1.5.

**Comment by jweisz** [comment]
This has been added in tjbotlib 1.5. Thanks.
