### ISSUE TITLE
how do I keep subsequent tj commands from running into each other

### ISSUE THREAD

**Issue by ssuppan** [ibmtjbot/tjbotlib#50]
I am having tj bot speak two sentences and then listen for a user response.
The issue I am having is that tj bot is speaking the first sentence and then only one or two words of the second sentence before it is cut off.  I observed that the code is continuing and not waiting for the text to speech to play.

**Comment by jweisz** [comment]
Try using the promise form of `tj.speak`:

```
tj.speak("hello").then({
  tj.speak("world");
});
```

(that's from memory, my apologies if the code doesn't work exactly as written).

**Comment by ssuppan** [comment]
Justin,
Thanks for getting back to me so quickly.  I did try the promise form and those two statements are still running into each other such that I hear about one or two words.  I was hoping to make an introduction with one speak command and then ask for something with another speak command.  After that, I want to listen for a code and then lookup the code in a database and then speak the person's first name.  Unfortunately, once the wav file is generated, control seems to continue immediately and does not wait until the wav file is completed playing.

**Comment by ssuppan** [comment]
I am able to hear the following through the speaker : aplay -D "plughw:0,0" /usr/share/sounds/alsa/Front_Center.wav.  Not sure why tj.speak( ) commands will not speak so clearly.

**Comment by ssuppan** [comment]
I am using a USB speaker provided with the tjbot maker kit that I purchased from AdaFruit.
https://www.adafruit.com/product/3369
The speaker is located at "plughw:0,0"

**Comment by ssuppan** [comment]
Justin,

I got it working.  Something in the node.js file was preventing the promises from working correctly.
When I copied another node.js test file from tjbot and replaced the minimum amount of logic, the promises worked correctly and the multiple speaking statements played correctly from the speaker.

Still not sure what went wrong.  Thanks for looking into this issue.
