### ISSUE TITLE
Left handed TJ

### ISSUE THREAD

**Issue by dariosm** [ibmtjbot/tjbotlib#54]
Hi there. I've recently assembled a TJ Bot, and after running somes recipes that uses the arm, I found that no matter how I place the servo, the movements are wrong.
By swapping default servo positions I got it right. Default are:
```
TJBot.prototype._SERVO_ARM_BACK = 500;
TJBot.prototype._SERVO_ARM_UP = 1400;
TJBot.prototype._SERVO_ARM_DOWN = 2300;
```
Swapping `BACK` and `DOWN` solves the problem, since the arm is in the left side of the bot.

**Comment by jweisz** [comment]
Is it possible you installed the servo upside-down? 🙃

Closing the issue since I think you figured it out.

**Comment by dariosm** [comment]
@jweisz nope, I installed it correctly and actually flip it just in case. The only way it would work with current `SERVO_ARM*` values, is by flipping the servo horizontally (which leaves the actual arm inside the bot :( )
Maybe it's a faulty servo, I don't know. If no one has this problem, then my bad!
