### ISSUE TITLE
Update versions of pigpio and rpi-ws281x-native?

### ISSUE THREAD

**Issue by stonebraker** [ibmtjbot/tjbotlib#55]
I got my tjbot as a gift last year, but didn't get around to playing with him until now. My 11 year old nephew constructed and wired him without assistance. What an awesome experience for him. I, however, had a little more difficulty due to my late start. :-)

It would appear that the version of node installed with Raspbian Buster won't properly build the pigpio or rpi-ws281x-native modules. In other recipes I tried, I was able to update package.json to reference the latest versions of these. But I can't do that in the tjbot bootstrap module. I was able to fanangle it by building them separately and copying them into the node_modules folder, but that defeats the point of bootstrapping.

Just wanted to make this recommendation on behalf of any new tjbot users that might come along. I appreciate the work you guys have put into this. It's really cool and a great learning tool for him and me.

Thanks a ton!

**Comment by mclellanpj** [comment]
Hello @stonebraker - would you mind posting the steps & commands used to update package.json to reference the latest versions of pigpio and rpi-ws281x-native pls?

**Comment by stonebraker** [comment]
Sure thing... I determined the latest build by visiting the packages' pages on npm.

Changed the pigpio dependency declaration to:
`"pigpio": "^1.2.3",`

And the rpi-ws281x-native declaration to"
`"rpi-ws281x-native": "^0.9.0",`

Hope this helps...

**Comment by jweisz** [comment]
Thanks for the feedback (and apologies for taking so long to get this done…). I just released a point release that has newer versions of these libraries specified: https://github.com/ibmtjbot/tjbotlib/releases/tag/v1.5.3
