### ISSUE TITLE
tjbot.js is looking for watson modules in the wrong location

### ISSUE THREAD

**Issue by CaskAle** [ibmtjbot/tjbotlib#63]
the file `node_modules/tjbot/lib/tjbot.js` is trying to include Watson modules from:
`import AssistantV2 from 'ibm-watson/assistant/v2.js'` It appears that there is a missing directory the path (dist). I think it should be: `import AssistantV2 from 'ibm-watson/dist/assistant/v2.js'` This holds true for all of the watson imports (6).

**Comment by CaskAle** [comment]
on further investigation, i think this may be due to the latest version of ibm-watson.  dropping back to a prior version has the modules in the proper location.

**Comment by jweisz** [comment]
This is the version of ibm-watson we're using, which should be latest from when tjbotlib 2.0.0 was released in November.

```
"ibm-watson": "^5.7.0",
```

Was there a newer release since then that moved the location of the imports?

**Comment by CaskAle** [comment]
Yes, ibm-watson @ 6.0.0 was placing the assistant code a level deeper under `dist/assistant/v2.js`. I see there is now a 6.0.1 it may have addressed the issue.  I need to verify.  In the mean time, 5.7.0 is working.  I have updated it to try and fix an issue that was, as it turns out, unrelated.  I will close this issue.
