### ISSUE TITLE
ES6 breaks compatibility with Node-Red

### ISSUE THREAD

**Issue by chunyianliew** [ibmtjbot/tjbotlib#67]
@jweisz. As of release 2.0.0 the TJBotLib has been packaged as an ES6 module.
This is making it very hard to to include the library in Node-Red as I discovered the hard way:
https://discourse.nodered.org/t/best-practice-to-import-an-es6-module-in-a-node-for-node-red/41014

Can you please share the rationale to package the library as an ES6 module?
Would it be possible to keep support for CommonJS?

**Comment by jweisz** [comment]
Hi @chunyianliew -- it seems ES6 modules might not be as ready for prime time as I originally thought, and I certainly didn't intend to break support for Node-Red. If you submit a PR to revert it back to a CommonJS module, I'll accept it. Thanks.

**Comment by chunyianliew** [comment]
@jweisz : Thank you for the update. I am not a experienced JS developer, my background is Java, but I am willing to give it a shot.

**Comment by jweisz** [comment]
@chunyianliew It took me way too long to get this, but I just published v2.0.2 of the library that packages it as a hybrid CommonJS / ES6 module. It requires one small change when loading via CommonJS, adding a reference to `.default` as follows: `const TJBot = require('tjbot').default`.

https://github.com/ibmtjbot/tjbotlib/releases/tag/v2.0.2
