### ISSUE TITLE
Version 2.0.2 missing from npmjs

### ISSUE THREAD

**Issue by jt-nti** [ibmtjbot/tjbotlib#69]
It doesn't look like 2.0.2 has been published to npmjs. I hit [problems which have been fixed in 2.0.2](https://github.com/ibmtjbot/tjbotlib/issues/67#issuecomment-948664634) and although I managed to work round the missing version on npmjs, it would be great to have it published if possible. Thanks.

**Comment by jweisz** [comment]
🤦 My bad. I just did an `npm publish` so you should be all set.

**Comment by jt-nti** [comment]
Awesome, thank you!
