### ISSUE TITLE
Discussion on what to do with IBM cloud services in tjbotlib

### ISSUE THREAD

**Issue by jweisz** [ibmtjbot/tjbotlib#87]
Given the churn we've seen in the IBM cloud sdk and now the incorporation of foundation model support into `ibm-watson-machine-learning` (with a corresponding WML service required in IBM cloud), does it make sense to:

- continue providing wrappers inside tjbotlib around the Watson APIs? or
- remove all Watson API stuff from tjbotlib and push it into the recipes, leaving tjbotlib to only abstract the hardware interface (e.g. led, mic, speaker, camera, servo)

**Comment by modcarroll** [comment]
This is in progress over in `tjbot` should we close this one?

**Comment by jweisz** [comment]
Yeah, we decided to focus only on core functionality in tjbotlib (hardware + STT/TTS) and push the fancier stuff (assistant, watsonx, etc.) out into the recipes.
