### ISSUE TITLE
Find alternative to Watson Language Translator

### ISSUE THREAD

**Issue by jweisz** [ibmtjbot/tjbotlib#89]
Watson Language Translator is now deprecated. It's unclear what the replacement service will be, if there will be one.

**Comment by modcarroll** [comment]
No specific service replacement; translation is being moved into LLMs

**Comment by jweisz** [comment]
Do you think we should keep the recipe then, and just base it off of a model that we know does a good job of translating?

**Comment by modcarroll** [comment]
Personally I don't think it's worth its own recipe; we could consider adding to the watsonx recipe the ability to customize the LLM with a variety of sample prompts and include translation as one of them. Let's discuss during our next call!

**Comment by modcarroll** [comment]
Todo:
- remove translator recipe
- add to watsonx recipe
- use latest version of granite in the c ode
- in the readme use llama and mistral (have them update the prompt themselves in the code and provide samples in the readme)

**Comment by jweisz** [comment]
The answer is "use watsonx.ai". :D
